language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: work@denwilliams.net
  on:
    tags: true
    repo: denwilliams/homenet-plugin-mqttpublish
  api_key:
    secure: WW8QKfTGvuQyNFnWHVxBO06nH23yOJ4vAxvqTU0SGMGZjqfJkiFFIy/cKkI7pxKOAfTFCGxO+VKPwpNQXGF6JbUO6qlVKMRtvJ/WfDSSk/O//QDV9xwsaBppAMLo1qUD/w122Ks6EZoPNim8Wxbar2oGfMUTIClOSsfgMUPfysaOeBOb1pDxumelEaFl8dCdW9Zk/PuU4fPjsx7/iozsoguZhfsMnTVPdp67sBRMxriS9Eul0IvCJ5RAjRLLZPAIdk/qhCM7Yrluw2BmyctnvQy0vyBNcDXMfM+Rn+t2WvBGWklcXMXLmX/mLU8gDYeuBMkI0H74J+s125czj4Ew2abcUcBlqlR1aXSsu5VJek9D/MCWaz3vt2R6M3thSGCLl+2q51RUQapaSBH82J4ttvY59UmpxP7v45vRsGzpl7BwB67u7F89WPD3SOPtnfDRRe9CBWMtLoc7Hg4Vic+m4WaBjG+/CH+N/LEj2gh4zAcSyHw6y0rrB8OpqMjmhtV4Vp/93B2SeQhTR9sX7mBQu7FS4ta46jyee42SHRi8i4LzdkLwoVf9hlH+T8hJn1rQkXICLOURh0buP8ZvAEnfGGiebh+jw2cZcAodYKczj1Iat+Js60ARlpOLcRMI6uRt2Wu0laSa3sOezCz+lImpJJ1mKbfDPsce+DRYkM/K1G8=
